# General settings and logging
project_name: "3D Object detection (DLCS)"
experiment_name: "Net upload test"
notes: "augmentation with random rotation, blurring, contrast. Linear warmup for 5 epochs, then cosine annealing. Trying on a vast rented GPU"

use_wandb: True

# Model settings
pretrained: False

# Training Hyperparameters
crop_batch_size: 4
dl_batch_size: 1
epochs: 100
learning_rate: 0.001
# scaler_init_scale: 
# scaler_growth_interval:

# Data settings
data_dir: "../subset_1_to_3_processed"
annotations_path: "../DLCSD24_Annotations_voxel_1_to_3.csv"
dl_workers: 8

# Logging and Checkpointing
last_model_save_path: "100_epochs_augmented_warmup_last.pt"

