# General settings and logging
project_name: "3D Object detection (DLCS)"
experiment_name: "3 subsets, no augmentation, warmup, cosine annealing"
notes: "Linear warmup for 5 epochs, then cosine annealing. Trying on a vast rented GPU. 3 dlcs subsets totaling 480 patients"

use_wandb: True

# Model settings
pretrained: False

# Training Hyperparameters
crop_batch_size: 3
dl_batch_size: 2
epochs: 150
learning_rate: 0.001
augment: False
validate_every: 10
# scaler_init_scale: 
# scaler_growth_interval:

# Data settings
data_dir: "../subset_1_to_3_processed"
annotations_path: "../DLCSD24_Annotations_voxel_1_to_3.csv"
dl_workers: 8

# Logging and Checkpointing
last_model_save_path: "150_epochs_augmented_warmup_last.pt"

