project_name: "dev_roi"
experiment_name: "DLCS again"
notes: "
        unmasked, resampled, pruned dataset (threshold pruning). 3 channel images with prev, curr and next slices.
        Augmentations are the following:                
        A.HorizontalFlip(p=0.5),
        A.ShiftScaleRotate(shift_limit=0.1, scale_limit=0.1, rotate_limit=10, p=0.5),
        A.RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1, p=0.5),
        CLAHE(p=0.4),
        "
use_wandb: True
augment: True
device: "cuda:1"
random_state: 123
amp: True
        
image_input_channels: 1
output_dim: 4

dl_workers: 4

batch_size: 16
epochs: 20
learning_rate: 0.0001
train_split_ratio: 0.7
val_test_split_ratio: 0.60 # test ratio is 1 - val_test_split_ratio
patience: 5

data_path: "/gwdata/users/aborghesi/DLCS/2d_1_to_6_resampled_pruned_threshold/"
annotation_path: "/gwdata/users/aborghesi/DLCS/2d_annotations_pruned_threshold.csv"

# data_path: "/gwdata/users/aborghesi/DLCS/2d_1_to_6_resampled/"
# annotation_path: "/gwdata/users/aborghesi/DLCS/2d_annotations.csv"

log_dir: "logs"
checkpoint_dir: "checkpoints"
visualization_dir: "visualizations"
# visualization_experiment_name: "resampled_extended_dataset/mobilenet/eigencam_adaptive_segmenter/"
visualization_experiment_name: "pruned_threshold/"
