experiment_name: "dev_roi"
image_input_channels: 1
output_dim: 4

dl_workers: 2

batch_size: 6
epochs: 2
learning_rate: 1e-4
dropout_rate: 0.5
use_wandb: False

data_path: "data/slices_segmentate_png"
annotation_path: "data/annotations.csv"
log_dir: "logs"
checkpoint_dir: "checkpoints"