project_name: "dev_roi"
experiment_name: "MN augment"
notes: "trying out data augmentation"
use_wandb: False

image_input_channels: 1
output_dim: 4

dl_workers: 1

batch_size: 1
epochs: 100
learning_rate: 0.0001
train_split_ratio: 0.7
val_test_split_ratio: 0.60 # test ratio is 1 - val_test_split_ratio
random_state: 123
patience: 15

data_path: "data/slices_segmentate_png"
annotation_path: "data/annotations.csv"
log_dir: "logs"
checkpoint_dir: "checkpoints"
visualization_dir: "visualizations"
# visualization_experiment_name: "bbox_and_gradcam"

model_checkpoint: "FasterRCNNMobileNet/checkpoint_epoch_best.pt"