project_name: "dev_roi"
experiment_name: "RN50 bg norm"
notes: "background normalization"

image_input_channels: 1
output_dim: 4

dl_workers: 3

batch_size: 4
epochs: 100
learning_rate: 0.0001
use_wandb: True
train_split_ratio: 0.7
val_test_split_ratio: 0.60 # test ratio is 1 - val_test_split_ratio
random_state: 123
patience: 15

data_path: "data/slices_segmentate_png"
annotation_path: "data/annotations.csv"
log_dir: "logs"
checkpoint_dir: "checkpoints"
visualization_dir: "visualizations/resnet50_bg_norm"
visualization_experiment_name: "bbox_and_gradcam"

model_checkpoint: "FasterRCNNResnet50/bg_norm/checkpoint_epoch_34.pt"